spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/job_portal
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080


spring.application.name=backend

spring.datasource.url=jdbc:postgresql://dpg-d755vuv5r7bs73d7ub1g-a:5432/anagha_db
spring.datasource.username=anagha_db_user
spring.datasource.password=uKSJh69TYbbYORKK3xZEa8CT0o59eXew

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yaswanthy81@gmail.com
spring.mail.password=jicxsgkabebxdlag
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true